language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - build-tools-27.0.3
    - android-23
    - extra-google-play-services
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-google-android-support
    - extra-coogle-google_play_services
    - sys-img-armeabi-v7a-android-21
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
